services:
  # 学生用 TODO アプリ
  - type: web
    name: suna-todo-student
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true

  # インストラクター用ダッシュボード
  - type: web
    name: suna-todo-instructor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn instructor_app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true